name: mallard
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/JakesMD/mallard

environment:
  sdk: ^3.11.0

dependencies:
  equatable: ^2.0.8

dev_dependencies:
  test: ^1.25.6
  test_beautifier: ^1.1.0
  very_good_analysis: ^10.1.0
