name: mallard_bloc
description: Take advantage of Mallards railway oriented programming to radically simplify bloc applications.
version: 0.0.1
repository: https://github.com/JakesMD/mallard/packages/mallard_bloc
issue_tracker: https://github.com/JakesMD/mallard/issues
topics: [mallard, bloc, result, task, error-handling]

resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  bloc: ^9.2.0
  equatable: ^2.0.8
  mallard: ^1.0.0

dev_dependencies:
  test: ^1.25.6
  test_beautifier: ^1.1.0
  very_good_analysis: ^10.1.0
